### ISSUE TITLE
Consider adding this to the Packagist archive

### ISSUE THREAD

**Issue by digi-brains** [nathancox/silverstripe-sortableuploadfield#4]
The beauty of adding your modules to the [Packagist](https://packagist.org/) archive is that people using it can add this package to their gitignore file and not mess with manually moving and tracking this module.

**Comment by spekulatius** [comment]
@nathancox is this something you would consider? Would make life easier...

**Comment by nathancox** [comment]
Wow, April 2015.  I need to figure out why I'm not seeing all my github notification emails.

Anyway, this is in packagist now as nathancox/sortableuploadfield.

**Comment by spekulatius** [comment]
Thank you :)

**Comment by sageworksstudio** [comment]
Thanks!
